using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DbdPerksRoullet.Enums.PerksColors {
    internal enum BlueEnums : int {

        //Survivor
        iconperks_anymeansnecessary = 0,
        iconperks_appraisal = 1,
        iconperks_babysitter = 2,
        iconperks_balancedlanding = 3,
        iconperks_bardicinspiration = 4,
        iconperks_betterthannew = 5,
        iconperks_bettertogether = 6,
        iconperks_bitethebullet = 7,
        iconperks_bloodpact = 8,
        iconperks_bloodrush = 9,
        iconperks_bond = 10,
        iconperks_breakdown = 11,
        iconperks_clairvoyance = 12,
        iconperks_counterforce = 13,
        iconperks_diversion = 14,
        iconperks_dramaturgy = 15,
        iconperks_empathy = 16,
        iconperks_exultation = 17,
        iconperks_fasttrack = 18,
        iconperks_finesse = 19,
        iconperks_flipflop = 20,
        iconperks_friendlycompetition = 21,
        iconperks_innerfocus = 22,
        iconperks_ironwill = 23,
        iconperks_leftbehind = 24,
        iconperks_lightweight = 25,
        iconperks_luckystar = 26,
        iconperks_momentofglory = 27,
        iconperks_parentalguidance = 28,
        iconperks_plunderersinstinct = 29,
        iconperks_potentialenergy = 30,
        iconperks_quickandquiet = 31,
        iconperks_redherring = 32,
        iconperks_situationalawareness = 33,
        iconperks_slipperymeat = 34,
        iconperks_smallgame = 35,
        iconperks_solidarity = 36,
        iconperks_technician = 37,
        iconperks_tenacity = 38,
        iconperks_troubleshooter = 39,
        iconperks_visionary = 40,
        iconperks_wakeup = 41,
        iconperks_weregonnaliveforever = 42,
        iconperks_windowsofopportunity = 43,
        iconperks_wiretap = 44,
        iconsperks_championoflight = 45,
        iconsperks_invocationweavingspiders = 46,
        t_iconperks_overcome = 47,

        //Killer
        iconperks_bamboozle = 48,
        iconperks_beastofprey = 49,
        iconperks_corruptintervention = 50,
        iconperks_deadlock = 51,
        iconperks_deerstalker = 52,
        iconperks_discordance = 53,
        iconperks_dissolution = 54,
        iconperks_dragonsgrip = 55,
        iconperks_enduring = 56,
        iconperks_fireup = 57,
        iconperks_floodofrage = 58,
        iconperks_forcedpenance = 59,
        iconperks_gearhead = 60,
        iconperks_geneticlimits = 61,
        iconperks_hangmanstrick = 62,
        iconperks_hexwretchedfate = 63,
        iconperks_hoarder = 64,
        iconperks_imallears = 65,
        iconperks_irongrasp = 66,
        iconperks_knockout = 67,
        iconperks_lethalpursuer = 68,
        iconperks_nowheretohide = 69,
        iconperks_overwhelmingpresence = 70,
        iconperks_predator = 71,
        iconperks_sloppybutcher = 72,
        iconperks_spiritfury = 73,
        iconperks_starstruck = 74,
        iconperks_stridor = 75,
        iconperks_superioranatomy = 76,
        iconperks_surge = 77,
        iconperks_thrillofthehunt = 78,
        iconperks_thwack = 79,
        iconperks_ultimateweapon = 80,
        iconperks_unbound = 81,
        iconperks_unnervingpresence = 82,
        iconperks_zanshintactics = 83
    }
}
