using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DbdPerksRoullet.Enums.PerksColors {
    internal enum PurpleEnum : int {

        //Survivor
        iconperks_aftercare = 0,
        iconperks_booncircleofhealing = 1,
        iconperks_borrowedtime = 2,
        iconperks_botanyknowledge = 3,
        iconperks_buckleup = 4,
        iconperks_calmspirit = 5,
        iconperks_camaraderie = 6,
        iconperks_chemicaltrap = 7,
        iconperks_dancewithme = 8,
        iconperks_darksense = 9,
        iconperks_deadhard = 10,
        iconperks_deception = 11,
        iconperks_dejavu = 12,
        iconperks_deliverance = 13,
        iconperks_desperatemeasures = 14,
        iconperks_detectiveshunch = 15,
        iconperks_empathicconnection = 16,
        iconperks_fixated = 17,
        iconperks_flashbang = 18,
        iconperks_fogwise = 19,
        iconperks_hardened = 20,
        iconperks_hope = 21,
        iconperks_kindred = 22,
        iconperks_lithe = 23,
        iconperks_luckybreak = 24,
        iconperks_madeforthis = 25,
        iconperks_momentofglor = 26,
        iconperks_nooneleftbehind = 27,
        iconperks_objectofobsession = 28,
        iconperks_offtherecord = 29,
        iconperks_openhanded = 30,
        iconperks_pharmacy = 31,
        iconperks_poised = 32,
        iconperks_premonition = 33,
        iconperks_provethyself = 34,
        iconperks_reactivehealing = 35,
        iconperks_reassurance = 36,
        iconperks_residualmanifest = 37,
        iconperks_resilience = 38,
        iconperks_resurgence = 39,
        iconperks_scenepartner = 40,
        iconperks_smashhit = 41,
        iconperks_solesurvivor = 42,
        iconperks_soulguard = 43,
        iconperks_spinechill = 44,
        iconperks_sprintburst = 45,
        iconperks_stillsight = 46,
        iconperks_teamworkcollectivestealth = 47,
        iconperks_teamworkpoweroftwo = 48,
        iconperks_thisisnothappening = 49,
        iconperks_uptheante = 50,
        iconperks_urbanevasion = 51,
        iconperks_wellmakeit = 52,
        iconsperks_illumination = 53,
        iconsperks_strengthinshadows = 54,
        t_iconperks_correctiveaction = 55,

        //Killer
        iconperks_awakenedawarenesss = 56,
        iconperks_bbqandchili = 57,
        iconperks_bittermurmur = 58,
        iconperks_bloodecho = 59,
        iconperks_bloodhound = 60,
        iconperks_brutalstrength = 61,
        iconperks_callofbrine = 62,
        iconperks_coulrophobia = 63,
        iconperks_darknessrevelated = 64,
        iconperks_deadmanswitch = 65,
        iconperks_distressing = 66,
        iconperks_forcedhesitation = 67,
        iconperks_hauntedground = 68,
        iconperks_hexbloodfavor = 69,
        iconperks_hexcrowdcontrol = 70,
        iconperks_hexfacethedarkness = 71,
        iconperks_hexplaything = 72,
        iconperks_hysteria = 73,
        iconperks_infectiousfright = 74,
        iconperks_insidious = 75,
        iconperks_leverage = 76,
        iconperks_lightborn = 77,
        iconperks_madgrit = 78,
        iconperks_mindbreaker = 79,
        iconperks_monitorandabuse = 80,
        iconperks_monstrousshrine = 81,
        iconperks_nooneescapesdeath = 82,
        iconperks_oppression = 83,
        iconperks_playwithyourfood = 84,
        iconperks_rapidbrutality = 85,
        iconperks_rememberme = 86,
        iconperks_ruin = 87,
        iconperks_savethebestforlast = 88,
        iconperks_spiesfromtheshadows = 89,
        iconperks_surveillance = 90,
        iconperks_territorialimperative = 91,
        iconperks_thatanophobia = 92,
        iconperks_thethirdseal = 93,
        iconperks_thrillingtremors = 94,
        iconperks_trailoftorment = 95,
        iconperks_undone = 96,
        iconperks_unrelenting = 97,
        iconperks_whispers = 98
    }
}
