using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DbdPerksRoullet.Enums.PerksColors {
    internal enum RedEnum : int {

        //Survivor
        iconperks_aceinthehole = 0,
        iconperks_adrenaline = 1,
        iconperks_alert = 2,
        iconperks_autodidact = 3,
        iconperks_backgroundplayer = 4,
        iconperks_blastmine = 5,
        iconperks_boilover = 6,
        iconperks_boonshadowstep = 7,
        iconperks_breakout = 8,
        iconperks_builttolast = 9,
        iconperks_cutloose = 10,
        iconperks_darktheory = 11,
        iconperks_decisivestrike = 12,
        iconperks_distortion = 13,
        iconperks_eyesofbelmont = 14,
        iconperks_forthepeople = 15,
        iconperks_headon = 16,
        iconperks_hyperfocus = 17,
        iconperks_innerstrength = 18,
        iconperks_leader = 19,
        iconperks_lightfooted = 20,
        iconperks_lowprofile = 21,
        iconperks_mettleofman = 22,
        iconperks_mirroredillusion = 23,
        iconperks_overzealous = 24,
        iconperks_plottwist = 25,
        iconperks_powerstruggle = 26,
        iconperks_pushthroughit = 27,
        iconperks_repressedalliance = 28,
        iconperks_rookiespirit = 29,
        iconperks_saboteur = 30,
        iconperks_scavenger = 31,
        iconperks_secondwind = 32,
        iconperks_selfcare = 33,
        iconperks_specialist = 34,
        iconperks_stakeout = 35,
        iconperks_streetwise = 36,
        iconperks_survivalinstincts = 37,
        iconperks_unbreakable = 38,
        iconperks_vigil = 39,
        iconperks_vittoriosgambit = 40,
        iconsperks_deadline = 41,
        iconsperks_wicked = 42,
        t_iconperks_boonexponential = 43,

        //Killer
        iconperks_agitation = 44,
        iconperks_alieninstinct = 45,
        iconperks_anursescalling = 46,
        iconperks_batteriesincluded = 47,
        iconperks_bloodwarden = 48,
        iconperks_coupdegrace = 49,
        iconperks_cruelconfinement = 50,
        iconperks_darkarrogance = 51,
        iconperks_darkdevotion = 52,
        iconperks_deathbound = 53,
        iconperks_devourhope = 54,
        iconperks_dominance = 55,
        iconperks_dyinglight = 56,
        iconperks_eruption = 57,
        iconperks_franklinsloss = 58,
        iconperks_furtivechase = 59,
        iconperks_gameafoot = 60,
        iconperks_generatorovercharge = 61,
        iconperks_hatred = 62,
        iconperks_hexretribution = 63,
        iconperks_hexundying = 64,
        iconperks_hubris = 65,
        iconperks_huntresslullaby = 66,
        iconperks_ironmaiden = 67,
        iconperks_makeyourchoice = 68,
        iconperks_mercilessstorm = 69,
        iconperks_nemesis = 70,
        iconperks_nowayout = 71,
        iconperks_popgoestheweasel = 72,
        iconperks_scourgehookgiftofpain = 73,
        iconperks_septictouch = 74,
        iconperks_shadowborn = 75,
        iconperks_terminus = 76,
        iconperks_tinkerer = 77,
        iconperks_unforeseen = 78,
    }
}
